version: '3.2'
services:
  apache:
    build: ../apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /var/www
        target: /var/www
    depends_on:
      - mysql
      - dnsmasq
    networks:
      backend:
        aliases:
          - web
  dnsmasq:
    build: ../dnsmasq
    ports:
      - "53535:53/tcp"
      - "53535:53/udp"
    cap_add:
      - NET_ADMIN
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: /var/lib/local-mysql
        target: /var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    networks:
      backend:
        aliases:
          - database
    environment:
      MYSQL_ROOT_PASSWORD: 8p85tsPrPRdCHuqc

networks:
  backend:
